apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: hnjjooka4-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:ada31b50de6ef71454a4d520bda4f05783e61728@sha256:d3914c5255c6d7fa282e28ccc2a4ce9ffc58aabb55f4c699d6009ec3ece7b2f5
          name: container-image
